apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sriramdevops85@gmail.com
    privateKeySecretRef:
      name: account-key-prod
    solvers:
    - http01:
       ingress:
         class: nginx